language: php

php:
  - '7.1'

before_install:
  - composer self-update
  - composer install
  - composer clear-cache

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
